# Generated by Django 4.0.2 on 2022-07-06 00:52

import audioop
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    def create_crawler(apps, schema_editor):
        Crawler = apps.get_model("crawlers", "Crawler")
        Crawler.objects.create(
            name="Gov bg",
            allowed_domain="gov.bg",
            start_url="https://gov.bg/bg/prestsentar/novini",
            start_url_search="https://gov.bg/bg/search?q=",
            url="https://gov.bg",
            css_all_newsdiv="div.item",
            css_search_newsdiv=".articles-tabs > ul:nth-child(1) > li",
            title_css=".view > h1::text",
            pub_date_css=".view > p:nth-child(3)::text",
            body_css=".view > p",
            image_xpath='//*[@id="lightgallery"]/li/img/@src',
        )

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crawler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("allowed_domain", models.CharField(max_length=100)),
                ("start_url", models.CharField(max_length=180)),
                ("start_url_search", models.CharField(max_length=180)),
                ("url", models.CharField(max_length=180)),
                ("css_all_newsdiv", models.CharField(max_length=180)),
                ("css_search_newsdiv", models.CharField(max_length=180)),
                ("title_css", models.CharField(max_length=180)),
                ("pub_date_css", models.CharField(max_length=180)),
                ("body_css", models.CharField(max_length=180)),
                ("image_xpath", models.CharField(max_length=180)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.RunPython(create_crawler),
    ]
